#JAXIONS MODULE TO RUN SIMULATIONS FROM PYTHON
import os, re, shlex


def _write_run_script(filename, ranks, threads, usa, grid, simu, phys, vqcp,
                      inco, out, extra=''):
    """Write an executable, vax-ex-style script for a generated simulation."""
    variables = (
        ('GRID', grid),
        ('SIMU', simu),
        ('PHYS', phys),
        ('VQCD', vqcp),
        ('INCO', inco),
        ('OUT', out),
        ('EXTRA', extra),
    )
    lines = [
        '#!/usr/bin/env bash',
        'set -o pipefail',
        '',
        '# Generated by pyaxions.simgen. Edit any option below before running.',
        f'RANKS={int(ranks)}',
        f'THREADS={int(threads)}',
        'OMP_DYNAMIC=FALSE',
        'OMP_PROC_BIND=spread',
        'OMP_PLACES=cores',
        f'USA={shlex.quote(usa.strip())}',
    ]
    lines.extend(f'{name}={shlex.quote(value.strip())}' for name, value in variables)
    lines.extend([
        '',
        'export OMP_NUM_THREADS="$THREADS" OMP_DYNAMIC OMP_PROC_BIND OMP_PLACES',
        '',
        'mpi() {',
        '    printf "Executing: mpirun %s -np %q -x OMP_NUM_THREADS=%q -x OMP_DYNAMIC -x OMP_PROC_BIND -x OMP_PLACES" "$USA" "$RANKS" "$THREADS"',
        '    printf " %q" "$@"',
        '    printf "\\n"',
        '    mpirun $USA -np "$RANKS" -x OMP_NUM_THREADS="$THREADS" -x OMP_DYNAMIC -x OMP_PROC_BIND -x OMP_PLACES "$@"',
        '}',
        '',
        'link_config() {',
        '    local src=$1 dst=$2 index=$3 find src_path',
        '    find=$(printf "%05d" "$index")',
        '    if [[ "$src" = /* ]]; then src_path=$src; else src_path="$(pwd)/$src"; fi',
        '    mkdir -p "$dst/m"',
        '    ln -sfn "$src_path/m/axion.$find" "$(pwd)/$dst/m/axion.$find"',
        '}',
        '',
        'usage() {',
        '    echo "Usage: $0 {create|run|continue|con|restart|redu|wkb|paxion|measfile} [arguments]"',
        '    echo "  create"',
        '    echo "  run [extra options]"',
        '    echo "  continue INDEX [extra options]"',
        '    echo "  con INDEX OUT_DIR [extra options]"',
        '    echo "  restart [extra options]"',
        '    echo "  redu INDEX NEW_SIZE [extra options]"',
        '    echo "  wkb INDEX ZF STEPS [extra options]"',
        '    echo "  paxion INPUT_DIR INDEX ZF [extra options]"',
        '    echo "  measfile [extra options]"',
        '}',
        '',
        'MODE=${1:-run}',
        'if (( $# )); then shift; fi',
        '',
        'case "$MODE" in',
        '  create)',
        '    mkdir -p out/m',
        '    rm -f out/m/axion.m.* out/m/axion.00* axion.log.*',
        '    export AXIONS_OUTPUT="$(pwd)/out/m"',
        '    mpi vaxion3d $GRID $SIMU $PHYS $VQCD $INCO $OUT --steps 0 --p3D 1 "$@" 2>&1 | tee out/log-create.txt',
        '    ;;',
        '  run)',
        '    mkdir -p out/m',
        '    rm -f out/m/axion.m.* out/m/axion.00* axion.log.*',
        '    export AXIONS_OUTPUT="$(pwd)/out/m"',
        '    mpi vaxion3d $GRID $SIMU $PHYS $VQCD $INCO $OUT $EXTRA "$@" 2>&1 | tee out/log-run.txt',
        '    ;;',
        '  continue)',
        '    index=${1:?continue requires INDEX}; shift',
        '    mkdir -p out/m',
        '    export AXIONS_OUTPUT="$(pwd)/out/m"',
        '    mpi vaxion3d $GRID $SIMU $PHYS $VQCD $OUT --index "$index" "$@" 2>&1 | tee out/log-continue.txt',
        '    ;;',
        '  con)',
        '    index=${1:?con requires INDEX}; out_dir=${2:?con requires OUT_DIR}; shift 2',
        '    link_config out "$out_dir" "$index"',
        '    export AXIONS_OUTPUT="$(pwd)/$out_dir/m"',
        '    mpi vaxion3d $GRID $SIMU $PHYS $VQCD $OUT --index "$index" "$@" 2>&1 | tee "$out_dir/log-con.txt"',
        '    ;;',
        '  restart)',
        '    mkdir -p out/m',
        '    export AXIONS_OUTPUT="${AXIONS_OUTPUT:-$(pwd)/out/m}"',
        '    mpi vaxion3d --restart $GRID $SIMU $PHYS $VQCD $OUT "$@" 2>&1 | tee out/log-restart.txt',
        '    ;;',
        '  redu)',
        '    index=${1:?redu requires INDEX}; new_size=${2:?redu requires NEW_SIZE}; shift 2',
        '    mpi redu $GRID $SIMU $PHYS $VQCD $OUT --index "$index" --redmp "$new_size" "$@"',
        '    ;;',
        '  wkb)',
        '    index=${1:?wkb requires INDEX}; zf=${2:?wkb requires ZF}; steps=${3:?wkb requires STEPS}; shift 3',
        '    link_config out wout "$index"',
        '    export AXIONS_OUTPUT="$(pwd)/wout/m"',
        '    mpi WKVaxion $GRID $SIMU $PHYS $VQCD $OUT --index "$index" --zf "$zf" --steps "$steps" "$@" 2>&1 | tee wout/log-wkb.txt',
        '    ;;',
        '  pax|paxion)',
        '    pax_src=${1:?paxion requires INPUT_DIR}',
        '    index=${2:?paxion requires INDEX}; zf=${3:?paxion requires ZF}; shift 3',
        '    mkdir -p pout/m',
        '    rm -f pout/m/axion.m.* pout/m/axion.00*',
        '    link_config "$pax_src" pout "$index"',
        '    export AXIONS_OUTPUT="$(pwd)/pout/m"',
        '    pax_options=$*',
        '    mpi paxion3d $GRID $SIMU $PHYS $VQCD $OUT --index "$index" --zf "$zf" $pax_options 2>&1 | tee pout/log-paxion.txt',
        '    ;;',
        '  measfile)',
        '    mpi vaxion3d $GRID $SIMU $PHYS $VQCD $INCO $OUT --dump 8 --measlistlog "$@" 2>&1 | tee log-meas.txt',
        '    ;;',
        '  -h|--help|help)',
        '    usage',
        '    ;;',
        '  *)',
        '    echo "Unknown mode: $MODE" >&2',
        '    usage >&2',
        '    exit 2',
        '    ;;',
        'esac',
        '',
    ])

    filename = os.fspath(filename)
    with open(filename, 'w', encoding='utf-8') as script:
        script.write('\n'.join(lines))
    os.chmod(filename, os.stat(filename).st_mode | 0o111)
    return os.path.abspath(filename)

#auxiliary function to find the last config file
def last_mfile(src='out'):
    cwd = os.getcwd()
    out_m_dir = cwd + f'/{src}/m'
    files = os.listdir(out_m_dir)

    indices = [int(filename.split('.')[-1]) for filename in files if filename.startswith('axion.') and not filename.startswith('axion.m.')]

    if indices:
        return max(indices)
    else:
        return None

def runsim(JAX, MODE='run', RANK=1, THR=1, USA=' --bind-to socket --mca btl_base_warn_component_unused  0', IDX=False, OUT_CON='out1', CON_OPTIONS='', PAX_OPTIONS='', PAX_SRC='out', WKB_OPTIONS='', VERB=False):
    """
    runsim(JAX, MODE='run', RANK=1, THR=1, USA=' --bind-to socket --mca btl_base_warn_component_unused  0', IDX=False, OUT_CON='out1', CON_OPTIONS='', PAX_OPTIONS='', PAX_SRC='out', WKB_OPTIONS='')

    1 - cleans the out/m directory of axion.m.files
    2 - creates, runs or continues jaxions simulations:

            - MODE = "create":  mpirun {USA} -np {RANK} -x OMP_NUM_THREADS={THR} vaxion3d {JAX} --steps 0 --p3D 1 2>&1 | tee log-create.txt
            - MODE = "run":     mpirun {USA} -np {RANK} -x OMP_NUM_THREADS={THR} vaxion3d {JAX} 2>&1 | tee log-run.txt
            - MODE = "con":     mpirun {USA} -np {RANK} -x OMP_NUM_THREADS={THR} vaxion3d {JAX} --index {IDX or last_mfile()} {CON_OPTIONS} 2>&1 | tee log-con.txt
            - MODE = "wkb":     mpirun {USA} -np {RANK} -x OMP_NUM_THREADS={THR} WKVaxion --index {IDX or last_mfile()} {minimal JAX flags} {WKB_OPTIONS} 2>&1 | tee log-wkb.txt
            - MODE = "paxion":  mpirun {USA} -np {RANK} -x OMP_NUM_THREADS={THR} paxion3d --index {IDX or last_mfile(PAX_SRC)} {minimal JAX flags} {PAX_OPTIONS} 2>&1 | tee log-paxion.txt

    *For "wkb" and "paxion", minimal flags extracted from JAX: --size, --depth, --zgrid, --prec, --steps, --wDz, --fftplan
     All physics/output flags go in WKB_OPTIONS or PAX_OPTIONS.
    *"wkb" always sources from out/m/ -> wout/m/
    *"paxion" sources from PAX_SRC/m/ -> pout/m/ (PAX_SRC='out' or 'wout')

    JAX         string  vaxion3d flags generated with simgen
    MODE        str     'run' (default), 'create', 'con', 'wkb', or 'paxion'
    RANK        int     number of MPI processes
    THR         int     number of OMP threads
    USA         str     mpirun options
    IDX         int     config file index for 'con', 'wkb', 'paxion' modes (uses last_mfile() if False)
    OUT_CON     str     output folder for 'con' mode (default: 'out1')
    CON_OPTIONS str     additional flags for 'con' mode
    PAX_OPTIONS str     paxion-specific flags, e.g. '--zf 150.0 --ftype axion --Rc 16.0 ...'
    PAX_SRC     str     source directory for paxion symlink: 'out' (default) or 'wout'
    WKB_OPTIONS str     WKVaxion-specific flags, e.g. '--zf 150.0 --steps 10000 ...'
    VERB        bool    print full mpirun command if True
    """
    if VERB:
        print('')
        print('')
        print('--------------------------------------------------------------------------------------------')
        print(f'Mode: {MODE} ')
        print('')

    read_params = JAX
    cwd = os.getcwd()

    N0_match      = re.search(r'--size (\d+)',        read_params)
    depth_match   = re.search(r'--depth (\d+)',       read_params)
    zgrid_match   = re.search(r'--zgrid (\d+)',       read_params)
    L0_match      = re.search(r'--lsize (\d+\.\d+)', read_params)
    msa0_match    = re.search(r'--msa (\d+\.\d+)',   read_params)
    prec_match    = re.search(r'--prec (\S+)',        read_params)
    steps_match   = re.search(r'--steps (\d+)',       read_params)
    wDz_match     = re.search(r'--wDz (\S+)',         read_params)
    fftplan_match = re.search(r'--fftplan (\d+)',     read_params)

    N0    = int(N0_match.group(1))
    depth = int(depth_match.group(1))
    L0    = float(L0_match.group(1))
    msa0  = float(msa0_match.group(1)) if msa0_match else None

    os.environ['OMP_NUM_THREADS'] = str(THR)

    def build_minimal_base():
        base = ''
        if N0_match:
            base += f' --size {N0}'
        if depth_match:
            base += f' --depth {depth}'
        if zgrid_match:
            base += f' --zgrid {zgrid_match.group(1)}'
        if prec_match:
            base += f' --prec {prec_match.group(1)}'
        if steps_match:
            base += f' --steps {steps_match.group(1)}'
        if wDz_match:
            base += f' --wDz {wDz_match.group(1)}'
        if fftplan_match:
            base += f' --fftplan {fftplan_match.group(1)}'
        ftype_match = re.search(r'--ftype (\S+)', read_params)
        if ftype_match:
            base += f' --ftype {ftype_match.group(1)}'
        return base

    def symlink_config(src_dir, dst_dir, find):
        symlink_src = f'{cwd}/{src_dir}/m/axion.{find}'
        symlink_dst = f'{cwd}/{dst_dir}/m/axion.{find}'
        if not os.path.exists(symlink_src):
            raise FileNotFoundError(
                f"Source config file not found: {symlink_src}\n"
                f"Make sure '{src_dir}/m/axion.{find}' exists."
            )
        if not os.path.exists(symlink_dst):
            os.symlink(symlink_src, symlink_dst)

    def mpirun(cmd):
        output = os.popen(f'mpirun {USA} -np {RANK} -x OMP_NUM_THREADS={THR} {cmd}')
        output.read()

    if MODE == 'create':
        os.popen('rm out/m/axion.m.*').read()
        if VERB:
            print('Overview: N=%d, MPI_RANKS=%d, L=%f, msa=%s' % (N0, RANK, L0, msa0))
            print(f'mpirun {USA} -np {RANK} -x OMP_NUM_THREADS={THR} vaxion3d {JAX} --steps 0 --p3D 1 2>&1 | tee log-create.txt')
        mpirun(f'vaxion3d {JAX} --steps 0 --p3D 1 2>&1 | tee log-create.txt')

    elif MODE == 'run':
        os.popen('rm out/m/axion.m.*').read()
        if VERB:
            print('Overview: N=%d, MPI_RANKS=%d, L=%f, msa=%s' % (N0, RANK, L0, msa0))
            print(f'mpirun {USA} -np {RANK} -x OMP_NUM_THREADS={THR} vaxion3d {JAX} 2>&1 | tee log-run.txt')
        mpirun(f'vaxion3d {JAX} 2>&1 | tee log-run.txt')

    elif MODE == 'con':
        extra_con_options = ''
        if '--size' not in CON_OPTIONS:
            extra_con_options += '--size %d ' % N0
        if '--depth' not in CON_OPTIONS:
            extra_con_options += '--depth %d ' % depth
        if '--msa' not in CON_OPTIONS and msa0 is not None:
            extra_con_options += '--msa %f ' % msa0
        extra_con_options += CON_OPTIONS

        os.makedirs(f'{OUT_CON}/m', exist_ok=True)
        os.environ['AXIONS_OUTPUT'] = f"{cwd}/{OUT_CON}/m"

        index = IDX if IDX else last_mfile('out')
        find  = f'{index:05d}'
        symlink_config('out', OUT_CON, find)

        if VERB:
            print(f'mpirun {USA} -np {RANK} -x OMP_NUM_THREADS={THR} vaxion3d {JAX} --index {index} {extra_con_options} 2>&1 | tee log-con.txt')
        else:
            print('Overview: N=%d, MPI_RANKS=%d, L=%f, msa=%s (data in %s)' % (N0, RANK, L0, msa0, OUT_CON))
        mpirun(f'vaxion3d {JAX} --index {index} {extra_con_options} 2>&1 | tee log-con.txt')

    elif MODE == 'wkb':
        os.makedirs('wout/m', exist_ok=True)
        os.environ['AXIONS_OUTPUT'] = f"{cwd}/wout/m"

        index = IDX if IDX else last_mfile('out')
        find  = f'{index:05d}'
        symlink_config('out', 'wout', find)

        if VERB:
            print(f'mpirun {USA} -np {RANK} -x OMP_NUM_THREADS={THR} WKVaxion --index {index}{build_minimal_base()} {WKB_OPTIONS} 2>&1 | tee log-wkb.txt')
        else:
            print('Overview: N=%d, MPI_RANKS=%d, L=%f (wkb, out -> wout)' % (N0, RANK, L0))
        mpirun(f'WKVaxion --index {index}{build_minimal_base()} {WKB_OPTIONS} 2>&1 | tee log-wkb.txt')

    elif MODE == 'paxion':
        if PAX_SRC not in ('out', 'wout'):
            raise ValueError(f"PAX_SRC must be 'out' or 'wout', got '{PAX_SRC}'")

        os.makedirs('pout/m', exist_ok=True)
        os.environ['AXIONS_OUTPUT'] = f"{cwd}/pout/m"

        index = IDX if IDX else last_mfile(PAX_SRC)
        find  = f'{index:05d}'
        symlink_config(PAX_SRC, 'pout', find)

        if VERB:
            print(f'mpirun {USA} -np {RANK} -x OMP_NUM_THREADS={THR} paxion3d --index {index}{build_minimal_base()} {PAX_OPTIONS} 2>&1 | tee log-paxion.txt')
        else:
            print('Overview: N=%d, MPI_RANKS=%d, L=%f (paxion, %s -> pout)' % (N0, RANK, L0, PAX_SRC))
        mpirun(f'paxion3d --index {index}{build_minimal_base()} {PAX_OPTIONS} 2>&1 | tee log-paxion.txt')

    if VERB:
        print('Done!')
        print('--------------------------------------------------------------------------------------------')


def simgen(N=256, zRANKS=1, prec='single', dev='cpu', fftplan=64, lowmem=False, prop='rkn4', spec=False, fspec=False, steps=1000000, wDz=1.0, sst0=10, lap=1,
           nqcd=7.0, fA=-1, msa=1.0, lamb=-1.0, ctf=128., L=256.0, ind3=1.0, notheta=False, wkb=-1., gam=0.0, dwgam=1.0,
           vqcd='vqcdC', vpq=0, mink=False, xtr='', prep=False, ic='lola', logi=0.0, cti=-1.11,
           index=-100, ict='lola', dump=10, meas=0, p3D=0, spmask=1, rmask=1.5, redmp=-1.0, wTime=-1.0,
           spKGV=15, printmask=False, ng0calib=1.25, cummask=0, normcore=False,
           p2Dmap=False, p2DmapE=False, p2DmapPE=False, p2DmapPE2=False, p2DmapYZ=False, slc=-1, strmeas=-1, measloop=-1,
           nologmpi=True, verbose=1, ftype='saxion', verb=False,
           SCRIPT='simu.sh', THR=1,
           USA=' --bind-to socket --mca btl_base_warn_component_unused 0', **kwargs):
    """
    simgen creates a string of command line flags to select options for vaxion3d

    Writes an executable vax-ex-style bash script and returns
    int (number of ranks), string (flags).

    options:

    N         int    256      number of grid points in x,y directions
    zRANKS    int    1        number of MPI processes along z direction
    prec      str    single   single or double
    dev       str    cpu      cpu or gpu (use --measCPU)
    lowmem    bool   False
    prop      str    rkn4     propagator/time integrator
    spec      str    False    spectral propagator 1 (only CPU atm)
    fspec     str    False    spectral propagator 2 (only CPU atm)
    steps     int    10000    number of time steps (max if --wDz is used)
    wDz       float  1.0      time interval set to dt = wDz/w_max
    sst0      int    10       time steps without strings before switch to theta
    lap       int    1        number of neighbours in Laplacian
    fftplan   int    64       specify FFT plan to speed up initialisation
    nqcd      float  7.0      index of ct-dependence of Topological Susceptibility
    fA        int    -1       if fA > 0 is given, the code uses the --qcd qcd option with fA as specified
    msa       float  1.0      use PRS strings with ms = msa/(dx R); overrides lambda!
    lamb      float  -1.0     use Physical strings with SI lambda; make >0; is overridden by --msa
    ctf       float  128.     final conformal time of simulations
    L         float  256.0    Physical length of x,y directions in ADM units
    ind3      float  1.0      coefficient multiplying axion mass^2
    notheta   bool   False    False/True will switch/not switch to theta-only simulations after strings
    wkb       float  -1.0     the final fields are wkb'ed to this c-time
    gam       float  0.0      damping
    dwgam     float  1.0      rho damping activated after artificial DW destruction
    vqcd      str             vqcd type: 'vqcdC','vqcdV','vqcd0','vqcdL','N2'
    vpq       str    0        2 for vPQ2
    prep      bool   False
    ic        str    lola     type of initial conditions
    logi      float  0.0      use this log ms/H to set the initial c-time
    cti       float  -1.11    initial c-time
    index     int    -100     will read axion.int initial conditions to continue the simulation
    ict
    dump
    meas
    p3D
    spmask
    rmask
    redmp
    wTime
    spKGV
    printmask
    ng0calib
    cummask
    p2Dmap
    p2DmapE
    p2DmapPE
    p2DmapPE2
    p2DmapYZ
    slc
    strmeas
    measloop
    nologmpi
    verbose
    verb
    SCRIPT    path   simu.sh  output filename for the generated script
    THR       int    1        OpenMP threads per MPI rank
    USA       str             additional mpirun options
    kwargs
    """
    ####################################################
    GRID = " --size %d --depth %d --zgrid %d" % (N, N//zRANKS, zRANKS)
    ####################################################
    SIMU = " --prec %s --device %s --prop %s --steps %d --wDz %f --sst0 %d --fftplan %d --ftype %s" % (prec, dev, prop, steps, wDz, sst0, fftplan, ftype)
    if verb:
        print('Using --ftype %s' % ftype)

    if not (spec or fspec):
        SIMU += ' --lap %d' % lap

    if lowmem:
        SIMU += ' --lowmem'
    if dev == 'gpu':
        SIMU += ' --measCPU'
    if spec:
        SIMU += ' --spec'
        if verb:
            print('Using spec propagator.')
    if fspec:
        SIMU += ' --fspec'
        if verb:
            print('Using fspec propagator.')
    ####################################################
    VQCP = ''
    if vqcd in ['vqcdC', 'vqcdV', 'vqcd0', 'vqcdL', 'N2']:
        VQCP += ' --%s' % vqcd
    else:
        if verb:
            print('Warning: VQCD not recognised!')
    if vpq == 2:
        VQCP += ' --vPQ2'
    if vqcd == 'vqcd0' and ind3 > 0:
        ind3 = 0.0
        if verb:
            print('Warning: vqcd0 -> ind3 reset to %f' % ind3)
    ####################################################
    if lamb > 0:
        tension = ' --llcf %f' % lamb
    else:
        tension = ' --msa %f' % msa
    PHYS = "%s --lsize %f --zf %f --ind3 %f" % (tension, L, ctf, ind3)
    noth = ''; wkbs = ''; gams = ''; dwgams = ''; mnk = ''
    if fA > 0:
        qcd = ' --qcd qcd --fA %d' % fA
    else:
        qcd = ' --qcd %f' % nqcd
    if notheta:
        noth = ' --notheta '
    if wkb > 0:
        wkbs = ' --wkb %f' % wkb
    if gam > 0:
        gams = ' --gam %f' % gam
    if dwgam > 0:
        dwgams = ' --dwgam %f' % dwgam
    if mink:
        mnk = ' --mink'
        if verb:
            print('Minkowski!')
    PHYS += qcd + noth + wkbs + gams + dwgams + mnk + xtr

    if normcore:
        kwargs['normcore'] = True
    #################################################### IC conditions
    if index >= 0:
        INCO = ' --index %d' % index
    else:
        if cti == -1.11:
            it = ' --logi %f' % logi
        else:
            it = ' --zi %f' % cti
        INCO = it + INCOgen(ict, verb, **kwargs)
    ####################################################
    OUT0 = ''
    if p2Dmap:
        OUT0 += ' --p2Dmap'
    if p2DmapE:
        OUT0 += ' --p2DmapE'
    if p2DmapPE and not p2DmapPE2:
        OUT0 += ' --p2DmapPE'
    if p2DmapPE2 and not p2DmapPE:
        OUT0 += ' --p2DmapPE2'
    if p2DmapYZ:
        OUT0 += ' --p2DmapYZ'
    if slc >= 0:
        OUT0 += ' --sliceprint %d' % slc
    if strmeas >= 0:
        OUT0 += ' --strmeas %d' % strmeas
    if measloop >= 0:
        OUT0 += ' --measloop %d' % measloop

    OUT1 = " --dump %d --meas %d --p3D %d " % (dump, meas, p3D)
    if redmp > 0:
        OUT1 += ' --redmp %d' % redmp

    OUTM = " --spmask %d --rmask %s --spKGV %d" % (spmask, str(rmask), spKGV)
    if printmask:
        OUTM += ' --printmask'
    if ng0calib != 1.25:
        OUTM += ' --ng0calib %f' % ng0calib
    if cummask != 0:
        OUTM += ' --cummask %d' % cummask

    OUT2 = " --verbose %d" % verbose
    if wTime > 0:
        OUT2 += '  --wTime %d' % wTime
    if nologmpi:
        OUT2 += ' --nologmpi'

    OUT = OUT0 + OUT1 + OUTM + OUT2
    if verb:
        print('PHYS =', PHYS)
        print('GRID =', GRID)
        print('SIMU =', SIMU)
        print('VQCD =', VQCP)
        print('INCO =', INCO)
        print('OUT  =', OUT)

    script_path = _write_run_script(
        SCRIPT, zRANKS, THR, USA, GRID, SIMU, PHYS, VQCP, INCO, OUT
    )
    print('Run script written to %s' % script_path)

    return zRANKS, PHYS + GRID + SIMU + VQCP + INCO + OUT


def INCOgen(ict, verb=False, **kwargs):
    def fif(ka, ja, xic):
        if ka in kwargs:
            xic += ' --%s ' % ja + str(kwargs[ka])
            if verb:
                print(xic)
        else:
            if verb:
                print('%s missing in kwargs: jaxion defaults will be used' % ka)
        return xic

    INCO = ''
    if ict == 'lola':
        INCO = ' --ctype %s' % ict
        if 'lola_string_multiplier' in kwargs:
            lr = 1
            if 'lolarandom' in kwargs:
                if kwargs['lolarandom']:
                    lr = 2
            INCO += ' --sIter %d --kcr %f' % (lr, kwargs['lola_string_multiplier'])
    if ict == 'spax':
        INCO = ' --ctype %s' % ict
    if ict == 'km':
        INCO = ' --ctype %s --mode0 1'%ict
    if ict == 'smooth':
        INCO = ' --ctype %s' % ict
        if 'smvar' in kwargs:
            INCO += ' --smvar %s' % (kwargs['smvar'])
        INCO = fif('mode0', 'mode0', INCO)
        INCO = fif('kMax', 'kMax', INCO)
        INCO = fif('kcr', 'kcr', INCO)
    if ict == 'cole':
        INCO = ' --ctype %s' % ict
        INCO = fif('kMax', 'kMax', INCO)
    if ict == 'tkachev':
        INCO = ' --ctype %s' % ict
        INCO = fif('kMax', 'kMax', INCO)
        INCO = fif('kcr', 'kcr', INCO)
    if ict == 'string':
        INCO = ' --ctype %s' % ict
        INCO = fif('sIter', 'sIter', INCO)
        if 'kmax' in kwargs:
            INCO = fif('kmax', 'kmax', INCO)
        if 'kcr' in kwargs:
            INCO = fif('kcr', 'kcr', INCO)
        if 'Bext' in kwargs:
            INCO = fif('Bext', 'Bext', INCO)
    if ict == 'thermal':
        INCO = ' --ctype %s' % ict
        INCO = fif('RPQ', 'RPQ', INCO)
        INCO = fif('kcr', 'kcr', INCO)

    if 'kickalpha' in kwargs:
        INCO += ' --kickalpha ' + str(kwargs['kickalpha'])
    if 'extrav' in kwargs:
        INCO += ' --extrav ' + str(kwargs['extrav'])
    if kwargs.get('normcore', False):
        INCO += ' --nncore'

    PREP = ''
    if 'preprop' in kwargs:
        PREP += ' --preprop'
        PREP = fif('prepcoe', 'prepcoe', PREP)
        PREP = fif('lz2e', 'lz2e', PREP)
        PREP = fif('prevqcdtype', 'prevqcdtype', PREP)
        PREP = fif('pregam', 'pregam', PREP)
        if 'icstudy' in kwargs:
            if kwargs['icstudy']:
                PREP += ' --icstudy'
    return INCO + PREP
